// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ55tIU7CamxwD3NJsT9d-Keh6PD57p1M',
    appId: '1:584685900716:web:f1bbbee1ca7c71dae8e009',
    messagingSenderId: '584685900716',
    projectId: 'chat-app-1efcc',
    authDomain: 'chat-app-1efcc.firebaseapp.com',
    storageBucket: 'chat-app-1efcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYNKMDpJFTTUw2P5NJM__-zdQLgPdd9FQ',
    appId: '1:584685900716:android:1af905e8ae2e7d59e8e009',
    messagingSenderId: '584685900716',
    projectId: 'chat-app-1efcc',
    storageBucket: 'chat-app-1efcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUfkAGDYV1aEu302DqM6-1GymrxeP44jA',
    appId: '1:584685900716:ios:0721604d36fc98d9e8e009',
    messagingSenderId: '584685900716',
    projectId: 'chat-app-1efcc',
    storageBucket: 'chat-app-1efcc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUfkAGDYV1aEu302DqM6-1GymrxeP44jA',
    appId: '1:584685900716:ios:820267b9f8fb1a2ce8e009',
    messagingSenderId: '584685900716',
    projectId: 'chat-app-1efcc',
    storageBucket: 'chat-app-1efcc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
