// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FquhjSQPHpuLqXvd8w2_5eX84yWB1Ss',
    appId: '1:387151914000:web:22c114f94e5f2094135695',
    messagingSenderId: '387151914000',
    projectId: 'chatsapp-de892',
    authDomain: 'chatsapp-de892.firebaseapp.com',
    storageBucket: 'chatsapp-de892.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyp1knVnD3DkA7D9Uc0Ar8MufnL8KL3xE',
    appId: '1:387151914000:android:78f93e28b403716c135695',
    messagingSenderId: '387151914000',
    projectId: 'chatsapp-de892',
    storageBucket: 'chatsapp-de892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBpbx0zJI41Fc-4pOt_9IMVVuKn0DThXo',
    appId: '1:387151914000:ios:cf590407b9d4acca135695',
    messagingSenderId: '387151914000',
    projectId: 'chatsapp-de892',
    storageBucket: 'chatsapp-de892.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBpbx0zJI41Fc-4pOt_9IMVVuKn0DThXo',
    appId: '1:387151914000:ios:68d593add2485411135695',
    messagingSenderId: '387151914000',
    projectId: 'chatsapp-de892',
    storageBucket: 'chatsapp-de892.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
