// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOjmw7DNW_gqXaFMVYiIMlRcgZPCLfGQ',
    appId: '1:875248742727:web:b8efc8351d0bf429171c62',
    messagingSenderId: '875248742727',
    projectId: 'chatapps-1e93d',
    authDomain: 'chatapps-1e93d.firebaseapp.com',
    storageBucket: 'chatapps-1e93d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyeaK4gfdO7BDKPW09b0J7f7ilnZ7hmWs',
    appId: '1:875248742727:android:decfcd9801ee518f171c62',
    messagingSenderId: '875248742727',
    projectId: 'chatapps-1e93d',
    storageBucket: 'chatapps-1e93d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4wjjN8WF7HwBXWP-tDoDBFo72hNX0_ik',
    appId: '1:875248742727:ios:71ca5749ac9fc260171c62',
    messagingSenderId: '875248742727',
    projectId: 'chatapps-1e93d',
    storageBucket: 'chatapps-1e93d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4wjjN8WF7HwBXWP-tDoDBFo72hNX0_ik',
    appId: '1:875248742727:ios:0a4d35b9e4997f77171c62',
    messagingSenderId: '875248742727',
    projectId: 'chatapps-1e93d',
    storageBucket: 'chatapps-1e93d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
